### ISSUE TITLE
Frequently changes location

### ISSUE THREAD

**Issue by adamboche** [kasramp/UbuntuIndicatorWeather#23]
I put in the lat/long coordinates manually. Several times per day, it changes from showing the location I entered to showing various distant locations around the world, often in other languages.

I do Preferences > OK, and that fixes it for the moment. But I'd rather not have to do this regularly. Not sure which version I have, but I believe it's the latest in the PPA.

Ubuntu 16.10.

**Comment by kasramp** [comment]
Thanks for reporting the issue. I believe this issue is related to a bug in our web service and currently working on it to resolve it. I will keep you updated on any changes.

**Comment by kasramp** [comment]
@adamboche I have fixed the issue on the API level and it is already deployed. It is expected to fix the problem and you don't even need to update your indicator app because changes are from backend. Please observe and do let me know whether the problem still persisting or not. 
For now I close the issue, feel free to reopen it.
