### ISSUE TITLE
Show more weather info on indicator-dropdown

### ISSUE THREAD

**Issue by khurshid-alam** [kasramp/UbuntuIndicatorWeather#26]
The old Ubuntu weather indicator(also written in python https://launchpad.net/weather-indicator) has very nice weather information displayed on indicator dropdown. It shows following information:

1. Humidity
2. Wind condition
3. Sunrise/Sunset etc

![weather-indicator-dropdown](http://i.imgur.com/BADDjGO.png)

The memory footprint is also very low; **~ 10-15MB**.

It uses **earthtools.org** (http://new.earthtools.org) to get location data and uses that location data with http://api.met.no to get sunrise/sunset info. Look at the source here: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/indicator-weather/wily/view/head:/bin/indicator-weather

Both services have deprecated (still working somehow). However for this kind of data we could always use OpenweatherMap api (http://openweathermap.org/api).

What do you think?

**Comment by kasramp** [comment]
@khurshid-alam  that's a great suggestion, I was also considering to do that. Even longtime back I have implemented some of those metrics at the api level, such as humanity, feelslike. Look at the sample api call here,
http://weather-api.madadipouya.com/current?lat=3.1390&lon=101.6869&fahrenheit=false
But the current priority is first to get rid of some of the bugs. 
For instance, you have reported earlier that sometimes the weather report get crazy. Or others reported that the location shows random places. These bugs are at the api level due to race condition. I am planning to open source the api so others can collaborate as well. 
Another problem that I am facing is that Ip-api.com blocked its service in Malaysia and now the indicator is totally useless there. I am also trying to find a workaround for that problem which is very severe, maybe moving the lat, lon finder to the in-house api as well.
But definitely I am considering to move forward with more metrics.

**Comment by khurshid-alam** [comment]
Nice to know that you are considering those metrics. Thanks.

For lat/long you could use freefeoip (https://freegeoip.net/) but all these services have limit.I would recommend to force user(or at least make it optional) to use his own api-key/token. That way the limit never exhausts. User only need to sign-up and get the api key. User can add it through preference or during set-up.

**Comment by kasramp** [comment]
@khurshid-alam I think very soon I can add those new metrics to the app.
Last few days, I was constantly working on creating a new API and finally successfully deployed it. So now all the indicator calls go to the new API. It is brand new, more robust and totally open source. It has way more metrics than previous one and has its own documentation page. So everyone can use it.
You can see all the new metrics in the new API here:
http://eris.madadipouya.com/#current

**Comment by khurshid-alam** [comment]
Awesome. Just installed 0.9. Everything works flawlessly now.
