### ISSUE TITLE
Please make refresh interval configurable via Preferences

### ISSUE THREAD

**Issue by tigran123** [kasramp/UbuntuIndicatorWeather#55]
I assume that the indicator is contacting the weather services not more frequently than once an hour. If this actually happens more frequently, then I would certainly like to reduce it to once an hour.

So, ideally, there should be a "Refresh interval" added to Preferences to allow users to set this to their liking. Some people may prefer to have refresh more frequently, like once in half an hour.

**Comment by kasramp** [comment]
Currently, API call interval is every 15 minutes. Unless the Openweather blocks the Eris service due to high usage as it is currently running on a free account. 
I don't think the interval should be user configurable, if there is not a weather change the user wouldn't notice anything until the condition change and/or switching network. 
Adding that option will possibly cause a big issue and that is getting blocked by Openweather more frequently. If only a small margin of users set the interval to let say every 2 minutes. Once that happens the service will be disrupted for all users because of few, accidentally, set a short interval.

**Comment by tigran123** [comment]
Ok, every 15 minutes is perfectly adequate. I thought it was much more frequent than that when I opened this issue :)
